apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: CLUSTER_NAME
  region: REGION_VALUE
  version: "1.15"

# us-east-1e isn't setup for EKS right now
availabilityZones: 
  - us-east-1a
  - us-east-1b
  - us-east-1c
  - us-east-1d

nodeGroups:
  - name: ng-1
    instanceType: m5.large
    desiredCapacity: 2
    ssh:
      allow: true 

fargateProfiles:
  - name: fp-dev
    selectors:
      - namespace: stream
  - name: cicd
    selectors:
      - namespace: cicd

