# Sample cluster declaration for a 50% split between spot/demand
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: playground
  region: us-east-1
  version: "1.15"

# us-east-1e isn't setup for EKS right now
availabilityZones: 
  - us-east-1a
  - us-east-1b
  - us-east-1c
  - us-east-1d

nodeGroups:
  - name: ng-1
    minSize: 2
    maxSize: 4
    instancesDistribution:
      maxPrice: 0.017
      instanceTypes: ["t3.nano, t3.micro", "t3.small"] # At least one instance type should be specified
      onDemandBaseCapacity: 0
      onDemandPercentageAboveBaseCapacity: 50
      spotInstancePools: 2

